# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH
unset USERNAME

eval `ssh-agent -s`

for file in ~/.ssh/*; do
    if [ -f $file  ]; then
        if grep 'id_rsa' <<< $file | grep -v ".pub" ; then
            ssh-add "$file" 
        fi

    fi
done
